
name: Run Automated Tests
on: [workflow_dispatch, push]
jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 19.0.0
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: APT Update
        run: sudo apt update -y
      - name: Install Node.js Dependencies
        run: npm install -y
      - name: Run Node.js Tests
        run: npm run test && echo "Exited with '$?'"

